### ISSUE TITLE
No CTRE in Java Path

### ISSUE THREAD

**Issue by Techno11** [pjreiniger/SnobotSim#12]
`java.lang.UnsatisfiedLinkError: no CTRE_PhoenixCCI in java.library.path`

Getting this error in this simulator.  Any Suggestions? Here is the full output:
````java.lang.UnsatisfiedLinkError: no CTRE_PhoenixCCI in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.ctre.phoenix.CTREJNIWrapper.<clinit>(CTREJNIWrapper.java:9)
	at com.ctre.phoenix.motorcontrol.can.BaseMotorController.<init>(BaseMotorController.java:51)
	at com.ctre.phoenix.motorcontrol.can.TalonSRX.<init>(TalonSRX.java:19)
	at org.usfirst.frc.team1322.robot.subsystems.LIFT.<init>(LIFT.java:17)
	at org.usfirst.frc.team1322.robot.Robot.<clinit>(Robot.java:32)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.snobot.simulator.robot_container.JavaRobotContainer.constructRobot(JavaRobotContainer.java:26)
	at com.snobot.simulator.Simulator.createRobot(Simulator.java:154)
	at com.snobot.simulator.Simulator.loadConfig(Simulator.java:117)
	at com.snobot.simulator.Simulator.startSimulation(Simulator.java:203)
	at com.snobot.simulator.Main.main(Main.java:46)
````

Windows 7 64 Bit Java JDK 1.8.121, Using the quick start package.

On A roboRIO in real life, this issue is usually caused by not having the `libCTRE_PhoenixCCI.so` file in the `C:\Users\<user>\wpilib\user\java\lib` folder.

**Comment by pjreiniger** [comment]
Simulator quickstart needs to be updated.  Probably will push this till after ship (plus a R&R period).  In the meantime, I think if you can download the [native package](https://github.com/pjreiniger/maven_repo/blob/master/com/snobot/simulator/ctre_override/0.8.0/ctre_override-0.8.0-native-windows.jar) (use the correct version for your quickstart to be safe.  Shouldn't matter for CTRE libraries) and extract the two DLL's to `<simulator_project>/dependencies/native`

The whole time I've been testing the quickstart I tie it to our robot (which then inherits its dependencies) causing me to miss this

**Comment by Techno11** [comment]
Ok thanks.  I intend to use this at home when I have no robot, and just need to test the code.

**Comment by Techno11** [comment]
That worked! Thank you so much!

**Comment by Gregadeaux** [comment]
Hi, I'm trying to get the simulator to work for the offseason, and I'm still receiving this error. I've got CTRE_PhoenixCCI.dll and CtreMockHooks.dll in my build folder already, but am still receiving this same error. Not using the quickstart, using 0.10. Any suggestions?

**Comment by RobotSpit** [comment]
Hello,
I had the same issues after ensuring those files were in the build path settings.  To resolve, I still had to add the folder containing those DLLs to the "Native Library Location" in the "Preferences" for the simulator project in Eclipse.

1. In the Package Explorer, right mouse-button click on the simulator project (Simulator10.0  or Simulator11.0) and select "properties".

2. In the pop-up properties window that opens after selecting "properties", select the "Java Build Path" catagory along the left.

3. Click the "Libraries" Tab.  Find and expand the "JRE System Library [jdk1.x.x_xxx] (whichever version of the jdk you are using) and expand the selection to see the components within it.

4. Then for the "Native Library Location" component property, assign the folder "SimulatorXX.X/dependencies/native" to that component property (where XX.X = 10.0 or 11.0, or whatever version of the Simulator that is being used.

5.  Now the CTRE drivers are found during the build and those LIBRARY Not Found messages are no longer encounteted.

Not sure if this is the 100% correct place to do this, but it resolved the same error messages for me.

Good Luck,
   Rufus (FRC Team1322 - Mentor)

**Comment by Auroric** [comment]
Currently using normal GradleRIO version, getting an error that is normally resolved by running Lifeboat with a RIO. However, it isn't the same as the ones shown here, and their solutions do not work.
