### ISSUE TITLE
Encoder getRate not working

### ISSUE THREAD

**Issue by cabobalot** [pjreiniger/SnobotSim#16]
When I try to use `encoder.getrate()` it returns a constant number around ~4.08. every other encoder function works however. I can get the distance and pulse count from each, and the gyro simulation works perfectly. What is there to do about this?

**Comment by pjreiniger** [comment]
It was never tested, I'll try to update it after our season is done. I don't think I can across it in any if the robots I tested over the summer

**Comment by pjreiniger** [comment]
Sorry for the delay.  Post season was met with full-force real world work.  Try 0.11 and let me know if it is better

**Comment by pjreiniger** [comment]
I think this was fixed, no follow up to prove otherwise
