### ISSUE TITLE
CTRE Issue 

### ISSUE THREAD

**Issue by Auroric** [pjreiniger/SnobotSim#23]
`Error Message: java.lang.UnsatisfiedLinkError: com.ctre.phoenix.motorcontrol.can.MotControllerJNI.Set_4(JIDDI)V
java.lang.UnsatisfiedLinkError: com.ctre.phoenix.motorcontrol.can.MotControllerJNI.Set_4(JIDDI)V`

This is normally resolved by running Lifeboat with the RIO connected to the computer. Is there a way to do it here?

**Comment by pjreiniger** [comment]
See #12. Working on fixing that with a more permanent solution

**Comment by pjreiniger** [comment]
I saw you posted in the other thread too.  Is this happening when you deploy to the robot, or when you try to run the simulator?

**Comment by Auroric** [comment]
This happens when trying to run the simulator. We had the exact same issue on the robot a few days ago but fixed it by running Lifeboat.

**Comment by pjreiniger** [comment]
Try updating the SnobotSim plugin to version 2018.05.23, and see if that helps anything.  Might not in this case.

**Comment by pjreiniger** [comment]
Actually, what version of CTRE are you trying to link against?

**Comment by Auroric** [comment]
No idea where to find the CTRE version, but its the most recent one.

**Comment by Auroric** [comment]
`> Task :runSnobotSim
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\com.snobot.simulator\snobot_sim_gui\0.11.0\e1a97cc451c5fddf77085a07846bd882b1f2e188\snobot_sim_gui-0.11.0-all.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\jfree\jcommon\1.0.16\376f19a7c317509a57dfc684cdfd4081db7c082c\jcommon-1.0.16.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\jfree\jfreechart\1.0.13\b5fbdc552c4caec3dac4b4dcbc10d119a194946e\jfreechart-1.0.13.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.11.0\bede79a3f150711634a3047985517431bf6499f2\log4j-api-2.11.0.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.11.0\e6b751e02120c08702d98750f6a80bc25343b7f5\log4j-core-2.11.0.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.18\e4a441249ade301985cb8d009d4e4a72b85bf68e\snakeyaml-1.18.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\com.miglayout\miglayout-swing\4.2\ca85067488e79a2078ba4eb8e2617653e9172388\miglayout-swing-4.2.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\com.miglayout\miglayout-core\4.2\70f2bfa2a077ee1632cc8229deffa1d942825c78\miglayout-core-4.2.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\org.opencv\opencv-jni\3.2.0\5c6a5b457a6a4071007cf53b8bab479933e01327\opencv-jni-3.2.0-all.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput\2.0.7\7795d3dbbcfecd03e3d2bf964b04c0cd042415f7\jinput-2.0.7.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\net.java.jutils\jutils\1.0.0\e12fe1fda814bd348c1579329c86943d2cd3c6a6\jutils-1.0.0.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\com.snobot.simulator\snobot_sim_java\0.11.0\e0bd8716659eba70a05c773e1f768a5f493349d5\snobot_sim_java-0.11.0-uber_native-windows.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\edu.wpi.first.ntcore\ntcore-jni\4.1.0\c1ad0b0938157416131580a988e5e7c2e976c983\ntcore-jni-4.1.0-all.jar;
  C:\Users\aaron\.gradle\caches\modules-2\files-2.1\edu.wpi.first.cscore\cscore-jni\1.3.0\9a49af3f76e0122517f53a65b2cd73c6452c0a9\cscore-jni-1.3.0-all.jar;
Info    C:/projects/snobotsim/snobot_sim_java/cpp/lib/SnobotSimJava/Jni/RegisterCallbacksJni.cpp:32 - Initializing the simulator
16:02:38.447 [RobotThread] FATAL com.snobot.simulator.Simulator - Unexpected exception, shutting down simulator
java.lang.NullPointerException: null
        at com.snobot.simulator.robot_container.JavaRobotContainer.startCompetition(JavaRobotContainer.java:32) ~[snobot_sim_gui-0.11.0-all.jar:?]
        at com.snobot.simulator.Simulator$2.run(Simulator.java:318) [snobot_sim_gui-0.11.0-all.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

Error I get when trying to run from gradle.

**Comment by Auroric** [comment]
Managed to get it working, and it no longer returns the Unsatisfied Link Error. However there appears to be issues with some of the other CTRE functions. Logs are here: [logs](https://pastebin.com/ctLHriRB).

**Comment by RocketRedNeck** [comment]
I submitted a similar issue (#41) and will withdraw it. But could @Auroric please post what you did to solve the link error? Spread the wealth!

**Comment by Auroric** [comment]
That was a while ago, kind of forgot. I probably wrote it down somewhere for the rest of my team, so I'll take a look in my notes @RocketRedNeck .

**Comment by pjreiniger** [comment]
Try the latest version. [This](https://github.com/pjreiniger/SnobotSimExamples/blob/master/JavaExample/build.gradle) is a good example to base your build file on.

The simulator currently supports CTRE 5.12.0

**Comment by RocketRedNeck** [comment]
I think I found out why: the following dialog was behind a bunch of windows
and as soon as I closed it, then things popped up.
[image: image.png]

Michael Kessel
Coach
The Bit Buckets
web.bitbuckets.org <http://www.bitbuckets.org>
FRC Team #4183
FLL Team #38905
VEX Team #5485

**Comment by RocketRedNeck** [comment]
Sorry to bug you again. Trying to key the VS Code debugger into running the
sim
The following configuration worked with the previous version (alpha
integration)
But the com.snobot.simulator.Main is no longer the entry point (does not
exist).
Using the frc.robot.Main does not seem right; how should we start the sim
through the debugger?
mk
{
"type": "java",
"name": "Debug (Launch)",
"request": "launch",
"cwd": "${workspaceFolder}",
"console": "internalConsole",
"stopOnEntry": false,
"mainClass": "com.snobot.simulator.Main",
"args": "",
"vmArgs": "-Djava.library.path=build/native_libs",
"env": {
"DYLD_LIBRARY_PATH": "build/native_libs"
}
}

Michael Kessel
Coach
The Bit Buckets
web.bitbuckets.org <http://www.bitbuckets.org>
FRC Team #4183
FLL Team #38905
VEX Team #5485

**Comment by pjreiniger** [comment]
I haven't tried to do that with VSCode, I'm still getting spun up on it (and using eclipse or intellij for everything else). I'll see if I can figure out how to get it hooked up with those launch things.

In the meantime if it helps, I know you can do debugging in eclipse. There are also ways that [you can tell gradle](https://stackoverflow.com/a/25619391) to wait for a remote debugger to attach on the command line. I don't know if VSCode supports that, but eclipse and intellij do.

**Comment by RocketRedNeck** [comment]
Is the main class for snobot still com.snobot.simulator.Main? Or has that changed? I think that as long as I know the entrypoint prior to snobot starting the Robot it should work just fine.
P.S., I think the PS4 controller mapping is not quite right (will be submitting a separate issue unless you have a quick tip)
